#!/bin/bash

SUBJECTS_DIR=freesurfer



for subj in $@
do 


fs_dir=$SUBJECTS_DIR/anat3T$subj
surf_dir=$fs_dir/surf

for hemi in rh lh
do 
for fwhm in 5
do

for dist in 1 2 3 4 5
do

out=$(($dist*5))


cp -r $surf_dir/${hemi}.R1_projdist$dist.fwhm$fwhm.fsaverage.mgh $surf_dir/${hemi}.curv.fwhm$out.fsaverage.mgh


done

done

done

done 
